UrskiyPeriodUserApp/Controllers/GraphicController.cs
using Microsoft.AspNetCore.Mvc;
using UrskiyPeriodBusinessLogic.ViewModels;

namespace UrskiyPeriodUserApp.Controllers
{
    public class GraphicController : Controller
    {
        public IActionResult Index()
        {
            if (Program.User == null)
            {
                return Redirect("~/Home/Enter");
            }
            var model = APIUser.GetRequest<GraphicViewModel[]>($"api/graphic/GetGraphic?userId={Program.User.Id}");
            return View(model);
        }
    }
}

UrskiyPeriodUserApp/Controllers/ReportController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UrskiyPeriodBusinessLogic.BindingModels;
using UrskiyPeriodBusinessLogic.ViewModels;

namespace UrskiyPeriodUserApp.Controllers
{
    public class ReportController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        public ReportController(IWebHostEnvironment environment)
        {
            _environment = environment;
        }

        public IActionResult Index()
        {
            if (Program.User == null)
            {
                return Redirect("~/Home/Enter");
            }
            ViewBag.RouteId = new MultiSelectList(APIUser.GetRequest<List<RouteViewModel>>
                ($"api/main/getroutes?UserId={Program.User.Id}"), "Id", "Name");
            return View();
        }

        public IActionResult Email()
        {
            if (Program.User == null)
            {
                return Redirect("~/Home/Enter");
            }
            return View();
        }

        [HttpPost]
        public IActionResult ReportDoc([Bind("RouteId")] ReportBindingModel model)
        {
            model.FileName = @"..\UrskiyPeriodUserAPP\wwwroot\report\Report.doc";
            APIUser.PostRequest("api/report/MakeDoc", model);

            var fileName = "Report.doc";
            var filePath = _environment.WebRootPath + @"\report\" + fileName;
            return PhysicalFile(filePath, "application/doc", fileName);
        }

        [HttpPost]
        public IActionResult ReportXls([Bind("RouteId")] ReportBindingModel model)
        {
            model.FileName = @"..\UrskiyPeriodUserAPP\wwwroot\report\Report.xls";
            APIUser.PostRequest("api/report/MakeExcel", model);

            var fileName = "Report.xls";
            var filePath = _environment.WebRootPath + @"\report\" + fileName;
            return PhysicalFile(filePath, "application/xls", fileName);
        }

        [HttpPost]
        public IActionResult ReportOnView([Bind("DateTo,DateFrom")] ReportBindingModel model)
        {
            model.UserId = Program.User.Id;
            model.FileName = @"..\UrskiyPeriodUserAPP\wwwroot\report\Report.pdf";
            APIUser.PostRequest("api/report/MakePdf", model);
            ViewBag.Report = model.FileName;
            return View("Email");
        }

        [HttpPost]
        public IActionResult SendMail([Bind("DateTo,DateFrom")] ReportBindingModel model)
        {
            model.UserId = Program.User.Id;
            model.UserEmail = Program.User.Email;
            model.FileName = @"..\UrskiyPeriodUserAPP\wwwroot\report\Report.pdf";
            APIUser.PostRequest("api/report/SendMail", model);
            return Redirect("~/Home/Index");
        }
    }
}

UrskiyPeriodUserApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UrskiyPeriodUserApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-
                   action="Index">Юрский период</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-
                        target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home" asp-action="Index">Маршруты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Report" asp-action="Index">Заповедники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Report" asp-action="Email">Отчёт</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Graphic" asp-action="Index">График</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home" asp-action="Privacy">Личные данные</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home" asp-action="Enter">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Home" asp-action="Register">Регистрация</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Юрский период - <a asp-area="" asp-controller="Home" asp-action="Privacy">Личные данные</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>